package sorcery.world;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fluids.FluidTank;
import sorcery.core.Sorcery;
import sorcery.lib.SorceryItems;
import sorcery.lib.SorcerySpells;
import sorcery.lib.SpellHelper;
import sorcery.tileentities.TileEntityForge;

public class NetherGenLavaHut extends WorldGenerator {
	protected Block[] GetValidSpawnBlocks() {
		return new Block[]{Blocks.lava};
	}
	
	public boolean LocationIsValidSpawn(World world, int i, int j, int k) {
		int distanceToAir = 0;
		Block checkID = world.getBlock(i, j, k);
		
		while(!checkID.isAir(world, i, j, k)) {
			distanceToAir++;
			checkID = world.getBlock(i, j + distanceToAir, k);
		}
		
		if(distanceToAir > 8) {
			return false;
		}
		j += distanceToAir - 1;
		
		Block blockID = world.getBlock(i, j, k);
		Block blockIDAbove = world.getBlock(i, j + 1, k);
		Block blockIDBelow = world.getBlock(i, j - 1, k);
		for(Block x : GetValidSpawnBlocks()) {
			if(blockIDAbove.isAir(world, i, j, k)) {
				return false;
			}
			if(blockID == x) {
				return true;
			} else if(blockID == Blocks.snow && blockIDBelow == x) {
				return true;
			}
		}
		return false;
	}
	
	public NetherGenLavaHut() {
	}
	
	public boolean generate(World world, Random rand, int i, int j, int k) {
		if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 13, j, k) || !LocationIsValidSpawn(world, i + 13, j, k + 12) || !LocationIsValidSpawn(world, i, j, k + 12)) {
			return false;
		}
		
		world.setBlock(i + 0, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 4, k + 2, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 3, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 4, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 5, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 6, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 7, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 8, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 9, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 10, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 11, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 4, k + 12, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 0, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 1, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 1, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 1, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 1, k + 5, Blocks.crafting_table, 0, 2);
		world.setBlock(i + 2, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 10, Blocks.furnace, 5, 2);
		world.setBlock(i + 2, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 2, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 2, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 2, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 5, k + 4, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 5, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 6, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 7, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 8, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 9, Blocks.nether_brick_stairs, 0, 2);
		world.setBlock(i + 2, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 2, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 0, k + 0, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 1, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 2, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 0, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 0, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 0, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 3, j + 1, k + 1, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 3, j + 1, k + 2, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 3, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 3, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 3, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 3, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 5, k + 4, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 3, j + 5, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 5, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 5, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 5, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 5, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 3, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 3, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 0, k + 0, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 0, k + 1, Blocks.soul_sand, 0, 2);
		world.setBlock(i + 4, j + 0, k + 2, Blocks.soul_sand, 0, 2);
		world.setBlock(i + 4, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 0, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 0, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 0, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 0, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 0, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 0, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 4, j + 1, k + 1, Blocks.nether_wart, 2, 2);
		world.setBlock(i + 4, j + 1, k + 2, Blocks.nether_wart, 2, 2);
		world.setBlock(i + 4, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 4, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 4, k + 10, Blocks.nether_brick, 2, 2);
		world.setBlock(i + 4, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 4, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 4, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 5, k + 4, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 4, j + 5, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 5, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 5, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 5, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 5, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 4, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 4, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 0, k + 0, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 1, Blocks.soul_sand, 0, 2);
		world.setBlock(i + 5, j + 0, k + 2, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 0, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 0, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 0, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 0, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 0, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 5, j + 1, k + 1, Blocks.nether_wart, 2, 2);
		world.setBlock(i + 5, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 5, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 5, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 5, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 5, k + 4, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 5, j + 5, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 5, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 5, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 5, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 5, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 5, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 5, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 0, k + 0, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 0, k + 1, Blocks.soul_sand, 0, 2);
		world.setBlock(i + 6, j + 0, k + 2, Blocks.soul_sand, 0, 2);
		world.setBlock(i + 6, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 0, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 0, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 0, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 0, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 0, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 0, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 6, j + 1, k + 1, Blocks.nether_wart, 2, 2);
		world.setBlock(i + 6, j + 1, k + 2, Blocks.nether_wart, 2, 2);
		world.setBlock(i + 6, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 6, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 6, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 6, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 5, k + 4, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 6, j + 5, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 5, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 5, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 5, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 5, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 6, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 6, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 0, k + 0, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 1, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 2, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 0, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 0, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 0, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 7, j + 1, k + 1, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 7, j + 1, k + 2, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 7, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 7, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 7, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 7, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 5, k + 4, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 7, j + 5, k + 5, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 5, k + 6, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 5, k + 7, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 5, k + 8, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 5, k + 9, Blocks.glass, 0, 2);
		world.setBlock(i + 7, j + 5, k + 10, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 7, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 7, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 8, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 8, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 8, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 5, k + 4, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 5, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 6, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 7, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 8, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 9, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 10, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 8, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 8, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 1, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 8, Blocks.flower_pot, 7, 2);
		world.setBlock(i + 9, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 2, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 3, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 9, j + 4, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 9, j + 4, k + 12, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 9, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 9, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 10, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 3, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 10, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 1, k + 11, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 10, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 4, k + 2, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 10, j + 4, k + 3, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 4, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 5, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 6, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 7, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 8, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 9, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 10, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 11, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 4, k + 12, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 10, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 10, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 11, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 3, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 11, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 1, k + 11, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 11, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 11, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 6, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 7, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 8, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 12, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 3, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 12, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 1, k + 11, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 12, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 12, j + 5, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 0, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 0, k + 3, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 4, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 5, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 6, Blocks.nether_brick_stairs, 3, 2);
		world.setBlock(i + 13, j + 0, k + 7, Blocks.nether_brick_stairs, 1, 2);
		world.setBlock(i + 13, j + 0, k + 8, Blocks.nether_brick_stairs, 2, 2);
		world.setBlock(i + 13, j + 0, k + 9, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 10, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 11, Blocks.nether_brick, 0, 2);
		world.setBlock(i + 13, j + 0, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 3, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 4, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 5, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 1, k + 9, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 10, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 11, Blocks.nether_brick_fence, 0, 2);
		world.setBlock(i + 13, j + 1, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 2, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 3, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 4, k + 12, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 7, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 8, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 9, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 10, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 11, Blocks.air, 0, 2);
		world.setBlock(i + 13, j + 5, k + 12, Blocks.air, 0, 2);
		
		for(int forint = 0; forint < 50; forint++) {
			if(world.getBlock(i + 1, j - forint, k + 3) == Blocks.lava)
				world.setBlock(i + 1, j - forint, k + 3, Blocks.nether_brick, 0, 2);
			
			if(world.getBlock(i + 9, j - forint, k + 3) == Blocks.lava)
				world.setBlock(i + 9, j - forint, k + 3, Blocks.nether_brick, 0, 2);
			
			if(world.getBlock(i + 1, j - forint, k + 11) == Blocks.lava)
				world.setBlock(i + 1, j - forint, k + 11, Blocks.nether_brick, 0, 2);
			
			if(world.getBlock(i + 9, j - forint, k + 11) == Blocks.lava)
				world.setBlock(i + 9, j - forint, k + 11, Blocks.nether_brick, 0, 2);
		}
		
		int chanceForHellFurnace = rand.nextInt(100);
		if(chanceForHellFurnace == 1) {
			world.setBlock(i + 2, j + 1, k + 10, Sorcery.machine, 4, 2);
		}
		
		int chanceForAnvil = rand.nextInt(5);
		if(chanceForAnvil == 1) {
			world.setBlock(i + 2, j + 1, k + 7, Blocks.anvil, 2, 2);
		}
		
		world.setBlock(i + 2, j + 1, k + 9, Sorcery.machine, 2, 2);
		TileEntityForge forge = (TileEntityForge)world.getTileEntity(i + 2, j + 1, k + 9);
		forge.getTanks()[0] = new FluidTank(new FluidStack(FluidRegistry.getFluidID("lava"), 10000), 10000);
		forge.setInventorySlotContents(4, new ItemStack(SorceryItems.hardClay, 1, rand.nextInt(12)));
		
		int chanceForHellForge = rand.nextInt(100);
		if(chanceForHellForge == 1) {
			world.setBlock(i + 2, j + 1, k + 9, Sorcery.machine, 3, 2);
		}
		
		world.setBlock(i + 2, j + 1, k + 4, Blocks.chest, 5, 2);
		TileEntityChest tile = (TileEntityChest)world.getTileEntity(i + 2, j + 1, k + 4);
		
		if(tile != null) {
			for(int in = 0; in < 4; ++in) {
				ItemStack item = this.pickCheckLootItem(rand);
				
				if(item != null) {
					tile.setInventorySlotContents(rand.nextInt(tile.getSizeInventory()), item);
				}
			}
			
			tile.setInventorySlotContents(rand.nextInt(tile.getSizeInventory()), new ItemStack(Items.flint_and_steel, 1));
			tile.setInventorySlotContents(rand.nextInt(tile.getSizeInventory()), new ItemStack(Blocks.obsidian, 14));
		}
		return true;
	}
	
	private ItemStack pickCheckLootItem(Random par1Random) {
		int var2 = par1Random.nextInt(12);
		switch(var2) {
			case 0:
				return new ItemStack(Items.lava_bucket, 1);
			case 1:
				return null;
			case 2:
				return new ItemStack(Items.skull, 1, 0);
			case 3:
				return new ItemStack(Items.nether_wart, par1Random.nextInt(8));
			case 4:
				return new ItemStack(Items.coal, 3);
			case 5:
				return new ItemStack(Items.coal, 1, 3);
			case 6:
				return new ItemStack(SorceryItems.cog, 1);
			case 7:
				return new ItemStack(SorceryItems.gemOnyx, 1);
			case 8:
				return new ItemStack(Items.blaze_rod, 1);
			case 9:
				return new ItemStack(Items.experience_bottle, 1);
			case 10:
				return new ItemStack(SorceryItems.bucketLiquidMagic, 1);
			case 11:
				int randInt = par1Random.nextInt(3);
				//if(randInt == 1)
					//return SpellHelper.instance.getPageFromSpellIDs(SorcerySpells.explode.spellID);
		}
		return null;
	}
}